---

- name: "Create {{ install_prefix }} directory"
  file:
    state: directory
    path: "{{ install_prefix }}"

- name: Unpack Node Exporter deployment archive
  unarchive:
    src: "{{ deployment_archive_url }}"
    dest: "{{ install_prefix }}"
    remote_src: yes

- name: Link unpacked Node Exporter to execution path
  file:
    state: link
    src: "{{ install_prefix }}/node_exporter-{{ software_version }}.linux-amd64/node_exporter"
    dest: /usr/local/bin/node_exporter

- name: Deploy Node Exporter systemd service template
  template:
    src: node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service

- name: Activate and start Node Exporter systemd service
  systemd:
    name: node-exporter
    enabled: true
    daemon_reload: yes
    state: started
