global:
  scrape_interval:     5s
  evaluation_interval: 5s

# Attach these labels to any time series or alerts when communicating with
# external systems (federation, remote storage, Alertmanager).
  external_labels:
        monitor: 'prometheus-grafana-exporter'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

#  - job_name: 'ansible-hosts'
#    scrape_interval: 10s
#    file_sd_configs:
#      - names: ['/etc/prometheus/dynamic/*.yml']

  - job_name: 'dynamic-hosts'
    scrape_interval: 10s
    file_sd_configs:
      - files:
          - /etc/prometheus/dynamic/*.yml
